### ISSUE TITLE
Application metric scrape requests from prometheus being traced

### ISSUE THREAD

**Issue by objectiser** [openshift-istio/origin#6]
When an istio proxied application is scraped for prometheus metrics, the scrape request is traced by the istio proxy and reported to the backend tracing system - even if the application itself has been instrumented in such a way to ignore those HTTP requests.

Istio 0.7.1 now supports disabling tracing for an application invocation (and scrape request) by providing a header "X-B3-Sampled: 0". However unfortunately prometheus does not enable custom header properties to be added to the scrape request.

One solution recommended by the prometheus maintainers is to use nginx. I've experimented with the following template being added to the `istio-system` namespace:
[prometheus-nginx.yml.txt](https://github.com/openshift-istio/origin/files/1964527/prometheus-nginx.yml.txt)

You then need to update the prometheus config to include `proxy_url: 'http://prometheus-nginx:9191'` for the relevant jobs that scrape services.

@knrc  As mentioned on IRC, this has been tested to ensure it does not sample the scrape requests - but I haven't yet checked that the application metrics are still being reported ok. I'll do further testing tomorrow. I tested it with [this example](https://github.com/objectiser/opentracing-prometheus-example/blob/master/simple/Istio-Kubernetes.md) (on k8s+istio) then performing a test request:

```
curl $ORDERMGR/buy

or

curl $ORDERMGR/sell
```
these commands randomly throw exceptions (e.g. account not found) to make the traces more interesting - so don't worry if you see a status 500.

**Comment by objectiser** [comment]
A more relevant template for the example on openshift-istio can be found [here](https://github.com/objectiser/opentracing-prometheus-example/blob/istiooc/simple/services-istio-kubernetes.yml) - with the appropriate annotation.

Unfortunately when I deployed the nginx template to openshift+istio I got: 
```
[gbrown@localhost istio]$ oc logs prometheus-nginx-55868b8595-qztss -n istio-system
2018/05/01 17:23:22 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```
Let me know if there is a simple fix for this, and I'll test further tomorrow.

**Comment by knrc** [comment]
@objectiser It looks like this may be another image that requires anyuid scc for its SA.

**Comment by objectiser** [comment]
@knrc Thanks - adding "serviceAccountName: prometheus" to the `prometheus-nginx` deployment fixed it.

**Comment by objectiser** [comment]
Verifed the metrics are being reported from envoy, istio and the example application - so looks good to go. So steps are:
* Deploy the prometheus-nginx.yml (feel free to rename the service if there is something more appropriate), with the added `serviceAccountName: prometheus`
* Add the proxy URL to the prometheus configmap in two locations, as shown below:

```
    # scrape config for service endpoints.
    - job_name: 'kubernetes-service-endpoints'
      proxy_url: 'http://prometheus-nginx:9191'
      kubernetes_sd_configs:
      - role: endpoints
```
and
```
    # Example scrape config for pods
    - job_name: 'kubernetes-pods'
      proxy_url: 'http://prometheus-nginx:9191'
      kubernetes_sd_configs:
      - role: pod
```
